app = "appwrite-fi"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  _APP_ENV = "production"

[[mounts]]
  source = "appwrite_data"
  destination = "/storage"

[http_service]
  internal_port = 80
  force_https = true

[[vm]]
  memory = "4096"
  cpus = 4
